### ISSUE TITLE
Bug with dialogue scale when hovering over it with the mouse

### ISSUE THREAD

**Issue by KolyaFedorenko** [KolyaFedorenko/WatchStormWeb#22]
Currently, when you hover over a dialog, it scales, which creates inconvenience for the user. 
This happens because the hover scale is declared in the `default-container` class:
```css
.default-container:hover {
  transform: scale(1.025);
  transition-duration: 500ms;
}
```
To fix this, you need to create separate classes for the elements that should scale on hover, and remove the scale declaration from the `default-container` class, for example:
```css
.movie:hover, .news:hover {
  transform: scale(1.025);
  transition-duration: 500ms;
}
```
