### ISSUE TITLE
Simplify container appearance animation

### ISSUE THREAD

**Issue by KolyaFedorenko** [KolyaFedorenko/WatchStormWeb#23]
The animation for containers appearing has not changed since the service launched and now feels outdated. At the moment, it uses `blur` and `scale`:
```css
@keyframes show-movies {
  from {
    filter: blur(10px);
    transform: scale(1.5);
  }

  to {
    filter: blur(0px);
    transform: scale(1);
  }
}
```
To simplify it, you can use the `opacity` property, and it also needs to be renamed because it is used not only to animate the appearance of movie containers, but also to animate the appearance of other containers too:
```css
@keyframes show-container {
  from {
    opacity: 0;
  }

  to {
    opacity: 1;
  }
}
```
